# Basic configurations for Jekyll
source: .
destination: ./_site
includes: ./_includes

# Update the baseurl to empty since your site is now at the root of amirhkarimi.com
baseurl: ""  # Empty because your custom domain no longer needs /website
url: "https://amirhkarimi.com"  # Your new custom domain

collections:
  projects:
    output: true

# Other typical Jekyll settings
markdown: kramdown  # Default markdown engine
